### ISSUE TITLE
Build failures on Kinetic build farm

### ISSUE THREAD

**Issue by jacquelinekay** [ros/roslisp_common#42]
`cl_urdf` fails to build binaries on the Kinetic build farm, including for 64-bit Ubuntu on x86. Can a maintainer take a look at the failing build soon? Otherwise I will blacklist the package on the farm until I am notified that the build has been fixed. Many thanks.

**Comment by airballking** [comment]
I will a have look at it.

**Comment by airballking** [comment]
I tried reproducing the error through a pre-release test. 

What I did: 
- roslisp in underlay
- roslisp_common as dependent

What broke:
- nothing

Puzzling.

**Comment by airballking** [comment]
It seems ```cl_urdf``` is the only package in ```roslisp_common``` that lists other packages in ```find package(catkin REQUIRED <here>)```. Maybe that causes the error on the buildfarm. I'll give it a try.

**Comment by airballking** [comment]
I could also not reproduce the error from the build-farm with ```roslisp_common``` in the underlay, and ```designator_integration``` in the overlay.

So, I guess the best thing to do is to try out the patched version ```cl_urdf```. I ran a pre-release test for the patched version, and all went fine. But, they also did for the broken one. So, who knows..

**Comment by airballking** [comment]
It seems that was the necessary fix. Yesterday, I realized that fix for Indigo, and I received several mails seeing that Indigo builds are back to normal. I will now release the same version of ```roslisp_common``` for Jade and Kinetic.

**Comment by jacquelinekay** [comment]
Good to hear you found the fix. @tfoote is planning to do a final sync for EOL'd Ubuntu distributions (saucy, utopic, vivid) for Indigo and Jade some time this week, so if you'd like to get the patched version into Jade make sure to do the release soon. Cheers!

**Comment by jacquelinekay** [comment]
oops, just saw your rosdistro PR

**Comment by airballking** [comment]
:)
